### ISSUE TITLE
Not adding to 100%

### ISSUE THREAD

**Issue by johan-schoeman** [jineshfrancs/BatteryProgressView#1]
There is something that I don't understand. If I set the maximum to 100 and then set the progress to 100 then it does not fill the circle with the availed value which should be zero. If comes short.  See your gif posted. It shown the same.....

**Comment by johan-schoeman** [comment]
...I meant 100... Not zero

**Comment by jineshfrancs** [comment]
I fixed the issue.Thank you for your response.

**Comment by johan-schoeman** [comment]
Thanks! It is working!
